# Generated by Django 4.2.8 on 2023-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="hall",),
        migrations.RemoveField(model_name="user", name="passing_year",),
        migrations.RemoveField(model_name="user", name="rollnumber",),
        migrations.RemoveField(model_name="user", name="room_number",),
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(unique=True),
        ),
    ]
